[app]
debug = false
hostname = 'http://127.0.0.1:8000'
api_prefix = '/api'
title = 'vCloud Director API'
description = 'REST API сервис, который совершает действия над ВМ через API vCloud Director'
version = '0.1.0'


[celery]
    [celery.beat_schedule]
        [celery.beat_schedule.'create all vm statistics every 5 minutes']
        task = 'create_all_vm_statistics'
        schedule = 300


[logger]
version = 1
disable_existing_loggers = false
    [logger.formatters]
        [logger.formatters.standard]
        format = """\
            Level: [{levelname}] | \
            Thread: [{threadName}:{thread}] | \
            Process: [{processName}:{process}] | \
            Logger: [{name}:{funcName}:{lineno}] | \
            Log: [{message}] | \
            Context: [{args}]"""
        style = '{'
    [logger.handlers]
        [logger.handlers.console]
        level = 'DEBUG'
        formatter = 'standard'
        class = 'logging.StreamHandler'
        stream ='ext://sys.stdout'
    [logger.loggers]
        [logger.loggers.app]
        handlers = ['console']
        level = 'DEBUG'
